#!/bin/bash

# Start odoo: fixme with supervisor for example
bin/supervisord
sleep 5
# robotframework tests
bin/pybot -v CONFIG:config_80.py robot/sale_stock_invoice_workflow.robot
# make documentation
bin/travis-sphinx build
